name: CI and Release
on:
  push:
    branches:
      - main
    # Trigger on version tags
    tags:
      - "v*"
  pull_request:
  merge_group:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Semver type of new version (major / minor / patch)"
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "lint run"

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "tests run"

  # Make a release if this is a manually trigger job, i.e. workflow_dispatch
  release:
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && contains(github.ref, 'refs/tags/v'))
    permissions: "write-all"
    steps:
      - uses: actions/checkout@v4
      - name: Version Release
        uses: ./.github/actions/version-release
        with:
          github-token: ${{secrets.DOCKER_TRIGGER}}
          version-bump: ${{inputs.version}}
